//! Emit a Rust `InputRecord` struct (and supporting enums) from an
//! inferred [`Schema`], so a caller can deserialize one CSV row into typed
//! Rust before it ever reaches Postgres.
//!
//! The mapping mirrors [`crate::infer`]'s type choices: `integer`/`bigint`
//! become `i32`/`i64`, `numeric` becomes `f64`, `boolean` becomes `bool`,
//! and date/timestamp/text stay `String` (no date crate is pulled in). A
//! nullable column is wrapped in `Option`. Every column flagged enum-like —
//! the "a loan is fixed or variable" case — becomes its own Rust enum with
//! `as_str`/`FromStr`, and the struct field takes that enum as its type.

use std::{collections::BTreeSet, fmt::Write as _};

use crate::infer::{Cardinality, ColType, Column, Schema};

/// One enum to generate: the Rust type name and its `(variant, csv value)`
/// pairs, in observed order.
struct EnumDef {
	type_name: String,
	variants: Vec<(String, String)>,
}

/// Build the full Rust source: a header comment, one enum per enum-like
/// attribute, then the `InputRecord` struct. Safe to write to a `.rs` file.
pub fn render(schema: &Schema) -> String {
	let mut type_names = BTreeSet::new();
	// The key is never treated as an enum, so only attributes contribute.
	let enums: Vec<(usize, EnumDef)> = schema
		.attrs
		.iter()
		.enumerate()
		.filter_map(|(i, col)| build_enum(col, &mut type_names).map(|def| (i, def)))
		.collect();

	let mut out = String::new();
	out.push_str("// Generated by csv-pg-schema from:\n");
	for src in &schema.sources {
		let _ = writeln!(out, "//   {src}");
	}
	out.push_str(
		"//\n// `InputRecord` mirrors one CSV row. Integer columns are sized\n\
		 // i32/i64 to match Postgres integer/bigint; numeric is f64; dates and\n\
		 // timestamps stay String. Enum-like columns become the enums below.\n\n",
	);

	for (_, def) in &enums {
		render_enum(&mut out, def);
	}

	out.push_str("#[derive(Debug, Clone, PartialEq)]\n");
	out.push_str("pub struct InputRecord {\n");
	render_field(&mut out, &schema.key, None);
	for (i, col) in schema.attrs.iter().enumerate() {
		let enum_name = enums
			.iter()
			.find(|(idx, _)| *idx == i)
			.map(|(_, def)| def.type_name.as_str());
		render_field(&mut out, col, enum_name);
	}
	out.push_str("}\n");
	out
}

/// Write one struct field, using `enum_name` as the base type when the
/// column is enum-like, else the column's scalar Rust type. Nullable
/// columns are wrapped in `Option`.
fn render_field(out: &mut String, col: &Column, enum_name: Option<&str>) {
	let base = enum_name.unwrap_or_else(|| col.ty.rust());
	let ty = if col.nullable {
		format!("Option<{base}>")
	} else {
		base.to_owned()
	};
	let _ = writeln!(out, "\tpub {}: {ty},", col.ident);
}

/// Turn a genuinely categorical column into an [`EnumDef`], or `None`. We
/// only enum-ify a `text` column whose cardinality lands in the `< 5`
/// "enum candidate" band (the README's "a loan is fixed or variable" case):
/// numeric, date, and high-cardinality columns — names especially — keep
/// their scalar Rust type. Variant names are de-duplicated within the enum
/// so two values that `PascalCase` to the same identifier still both appear.
fn build_enum(col: &Column, type_names: &mut BTreeSet<String>) -> Option<EnumDef> {
	if col.ty != ColType::Text || col.profile.cardinality() != Cardinality::Enum {
		return None;
	}
	let values = col.enum_values.as_ref()?;
	let type_name = unique(&to_pascal(&col.ident), type_names);
	let mut used = BTreeSet::new();
	let variants = values
		.iter()
		.map(|v| (unique(&to_pascal(v), &mut used), v.clone()))
		.collect();
	Some(EnumDef {
		type_name,
		variants,
	})
}

fn render_enum(out: &mut String, def: &EnumDef) {
	let name = &def.type_name;
	out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
	let _ = writeln!(out, "pub enum {name} {{");
	for (variant, value) in &def.variants {
		let _ = writeln!(out, "\t/// CSV value: {value:?}");
		let _ = writeln!(out, "\t{variant},");
	}
	out.push_str("}\n\n");

	let _ = writeln!(out, "impl {name} {{");
	out.push_str("\t#[must_use]\n");
	out.push_str("\tpub const fn as_str(self) -> &'static str {\n");
	out.push_str("\t\tmatch self {\n");
	for (variant, value) in &def.variants {
		let _ = writeln!(out, "\t\t\tSelf::{variant} => {value:?},");
	}
	out.push_str("\t\t}\n\t}\n}\n\n");

	let _ = writeln!(out, "impl std::str::FromStr for {name} {{");
	out.push_str("\ttype Err = String;\n\n");
	out.push_str("\tfn from_str(s: &str) -> Result<Self, Self::Err> {\n");
	out.push_str("\t\tmatch s {\n");
	for (variant, value) in &def.variants {
		let _ = writeln!(out, "\t\t\t{value:?} => Ok(Self::{variant}),");
	}
	let _ = writeln!(
		out,
		"\t\t\tother => Err(format!(\"unknown {name}: {{other}}\")),"
	);
	out.push_str("\t\t}\n\t}\n}\n\n");
}

/// `PascalCase` a CSV value or identifier into a Rust type/variant name,
/// splitting on any run of non-alphanumeric characters. A leading digit is
/// prefixed with `V`; an empty result becomes `Unknown`. Rust keywords that
/// would be illegal as a bare identifier get a trailing underscore.
fn to_pascal(s: &str) -> String {
	let mut out = String::new();
	for word in s.split(|c: char| !c.is_ascii_alphanumeric()) {
		let mut chars = word.chars();
		if let Some(first) = chars.next() {
			out.extend(first.to_uppercase());
			out.extend(chars);
		}
	}
	if out.is_empty() {
		return "Unknown".to_owned();
	}
	if out.as_bytes()[0].is_ascii_digit() {
		out.insert(0, 'V');
	}
	if matches!(out.as_str(), "Self" | "Super" | "Crate") {
		out.push('_');
	}
	out
}

/// Ensure `name` is unique within `used`, appending `2`, `3`, … on clash,
/// then record it.
fn unique(name: &str, used: &mut BTreeSet<String>) -> String {
	let mut candidate = name.to_owned();
	let mut n = 2u32;
	while used.contains(&candidate) {
		candidate = format!("{name}{n}");
		n += 1;
	}
	used.insert(candidate.clone());
	candidate
}

#[cfg(test)]
mod tests {
	use super::{render, to_pascal};
	use crate::infer::{ColType, Column, Profile, Schema};

	fn profile() -> Profile {
		Profile {
			non_null: 0,
			null_count: 0,
			distinct: 0,
			distinct_overflow: false,
			enum_cap: 32,
			num_range: None,
			num_scale: None,
			decimals: None,
			temporal_range: None,
			len_range: None,
			classes: crate::infer::CharClasses {
				any: false,
				all_ascii: true,
				no_lower: true,
				no_upper: true,
				all_alpha: true,
				all_digit: true,
				all_alnum: true,
				has_letter: false,
			},
		}
	}

	fn col(ident: &str, ty: ColType, nullable: bool, enums: Option<&[&str]>) -> Column {
		Column {
			header: ident.to_owned(),
			ident: ident.to_owned(),
			ty,
			nullable,
			enum_values: enums.map(|e| e.iter().map(ToString::to_string).collect()),
			profile: profile(),
		}
	}

	#[test]
	fn pascal_cases_values() {
		assert_eq!(to_pascal("interest_only"), "InterestOnly");
		assert_eq!(to_pascal("fixed"), "Fixed");
		assert_eq!(to_pascal("USD"), "USD");
		assert_eq!(to_pascal("Hopper, Grace"), "HopperGrace");
		assert_eq!(to_pascal("123abc"), "V123abc");
		assert_eq!(to_pascal("!!!"), "Unknown");
		assert_eq!(to_pascal("self"), "Self_");
	}

	#[test]
	fn renders_struct_and_enum() {
		let schema = Schema {
			name: "account".to_owned(),
			key: col("account_id", ColType::Integer, false, None),
			attrs: vec![
				col("balance", ColType::Numeric, false, None),
				col("credit_limit", ColType::Bigint, true, None),
				col(
					"loan_type",
					ColType::Text,
					false,
					Some(&["fixed", "variable", "interest_only"]),
				),
			],
			sources: vec!["m1.csv".to_owned()],
		};
		let out = render(&schema);
		// Integer/bigint split, numeric -> f64, nullable -> Option.
		assert!(out.contains("pub account_id: i32,"));
		assert!(out.contains("pub balance: f64,"));
		assert!(out.contains("pub credit_limit: Option<i64>,"));
		// Enum-like column uses the generated enum as its field type.
		assert!(out.contains("pub loan_type: LoanType,"));
		assert!(out.contains("pub enum LoanType {"));
		assert!(out.contains("InterestOnly,"));
		assert!(out.contains("Self::Fixed => \"fixed\","));
		assert!(out.contains("\"variable\" => Ok(Self::Variable),"));
	}
}
