//! Render an inferred [`Schema`] as Postgres DDL in the temporal,
//! one-table-per-attribute style (see `contact.sql` in the reference
//! repos): a `request` table for provenance, an `account` entity keyed by
//! its natural key, and one `(id, during)` history table per attribute
//! with `UNIQUE (id, during WITHOUT OVERLAPS)`.

use std::fmt::Write as _;

use crate::infer::{Column, Schema};

/// Build the full `CREATE` script. Safe to feed straight to
/// `psql -f` or to `Client::batch_execute`.
pub fn render(schema: &Schema) -> String {
	let s = &schema.name;
	let mut out = String::new();

	out.push_str("/* Generated by csv-pg-schema from:\n");
	for src in &schema.sources {
		let _ = writeln!(out, "     {src}");
	}
	out.push_str("\n   Temporal, one-table-per-attribute design: each mutable\n");
	out.push_str("   attribute keeps its own history keyed by (id, during) with\n");
	out.push_str("   UNIQUE (id, during WITHOUT OVERLAPS). Apply with psql -f. */\n\n");

	let _ = writeln!(out, "CREATE SCHEMA {s};\n");
	out.push_str("/* Needed so UNIQUE (id, during WITHOUT OVERLAPS) can build its\n");
	out.push_str("   GiST exclusion index over the non-range leading column. */\n");
	out.push_str("CREATE EXTENSION IF NOT EXISTS btree_gist;\n\n");

	out.push_str("/* One row per processed CSV: where it came from and the\n");
	out.push_str("   observation instant shared by every range it writes. */\n");
	let _ = writeln!(
		out,
		"CREATE TABLE {s}.import_request\n\
		 (\n\
		 \tid        integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY,\n\
		 \tsource    text        NOT NULL,\n\
		 \tat        timestamptz NOT NULL,\n\
		 \tloaded_at timestamptz NOT NULL DEFAULT now()\n\
		 );\n"
	);

	out.push_str("/* The account entity. Its surrogate id threads every attribute\n");
	out.push_str("   history together; the natural key from the CSV stays unique. */\n");
	let _ = writeln!(
		out,
		"CREATE TABLE {s}.account\n\
		 (\n\
		 \tid         integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY,\n\
		 \t{key} {kty} NOT NULL,\n\
		 \trequest_id integer NOT NULL REFERENCES {s}.import_request (id),\n\
		 \tUNIQUE ({key})\n\
		 );\n",
		key = schema.key.ident,
		kty = schema.key.ty.sql(),
	);

	for col in &schema.attrs {
		render_attr(&mut out, s, col);
	}
	out
}

fn render_attr(out: &mut String, schema: &str, col: &Column) {
	if let Some(values) = &col.enum_values {
		let _ = writeln!(
			out,
			"/* enum-like ({} distinct observed): {} */",
			values.len(),
			values.join(" | ")
		);
	}
	let nullable = if col.nullable { "" } else { " NOT NULL" };
	let _ = writeln!(
		out,
		"CREATE TABLE {schema}.account_{ident}\n\
		 (\n\
		 \tid         integer   NOT NULL REFERENCES {schema}.account (id),\n\
		 \t{ident}    {ty}{nullable},\n\
		 \tduring     tstzrange NOT NULL DEFAULT tstzrange(now(), 'infinity'),\n\
		 \trequest_id integer   NOT NULL REFERENCES {schema}.import_request (id),\n\
		 \tPRIMARY KEY (id, during),\n\
		 \tUNIQUE (id, during WITHOUT OVERLAPS)\n\
		 );\n",
		ident = col.ident,
		ty = col.ty.sql(),
	);
}
